### PR TITLE
Add argparse, directory argument and duplicate checking

### PR DESCRIPTION
**Pull request by memory-hunter**
The script now takes argument of a folder which can be full of MLD files, so it can do bunch of files
Added duplicate music check because some were present
Added argparse for better usage

### CODE REVIEW

**Comment by kagekiyo7** [comment]
Check the code diff again.

**Comment by memory-hunter** [comment]
@kagekiyo7 please check now

**Comment by kagekiyo7** [comment]
This tool targets a single file containing multiple mlds, so need to separate the script.
(Or you can develop it as your own fork)

**Comment by memory-hunter** [comment]
How about this?

**Comment by kagekiyo7** [comment]
ok. 
In addition, please update the readme.

**Comment by memory-hunter** [comment]
Is this good?

**Comment by memory-hunter** [comment]
Are you going to merge this? I want to delete my fork

**Comment by kagekiyo7** [comment]
I sent the code review.

**Pull request merged**
